import {
    IconTargetArrow, IconRocket, IconBrandGoogle, IconBrandFacebook,
    IconCode, IconPalette, IconBrandWordpress, IconShoppingBag,
    IconLayout, IconDeviceDesktop,
    IconSearch, IconMapPin, IconShoppingCart, IconSettings, IconFileText,
    IconLink, IconReportAnalytics, IconRobot,
    IconBrush, IconPhoto, IconAd, IconSparkles, IconPencilPlus,
    IconBrandInstagram, IconBrandLinkedin, IconBrandYoutube,
    IconUsers, IconVideo, IconSpeakerphone,
    IconSettingsAutomation, IconDatabase, IconMail, IconFilter,
    IconChartBar, IconBulb,
    IconBriefcase, IconTrendingUp, IconBuildingStore, IconWorldWww
} from '@tabler/icons-react';

const serviceCategories = [
    {
        slug: 'digital-marketing',
        name: 'Digital Marketing Services',
        shortName: 'Digital Marketing',
        description: 'Data-driven digital marketing strategies that deliver measurable growth and maximum ROI for your business.',
        icon: IconTargetArrow,
        color: 'blue',
        heroImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1920&q=80',
        stats: [
            { value: '300%', label: 'Average ROI' },
            { value: '500+', label: 'Campaigns Managed' },
            { value: '150+', label: 'Happy Clients' },
            { value: '10M+', label: 'Leads Generated' },
        ],
        subServices: [
            {
                slug: 'performance-marketing',
                name: 'Performance Marketing',
                description: 'Results-oriented marketing campaigns focused on measurable outcomes — conversions, leads, and revenue. We optimize every rupee spent to deliver maximum ROI.',
                icon: IconChartBar,
                heroImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1920&q=80',
                features: ['Conversion Tracking & Attribution', 'Multi-Channel Campaign Management', 'A/B Testing & Optimization', 'ROI-Focused Budget Allocation', 'Real-Time Performance Dashboards', 'Cost Per Acquisition Optimization'],
                benefits: ['Maximize return on ad spend', 'Data-driven decision making', 'Transparent performance reporting', 'Scalable growth strategies'],
            },
            {
                slug: 'growth-marketing',
                name: 'Growth Marketing',
                description: 'Full-funnel growth strategies that combine creative experimentation with data analysis to drive sustainable business growth at every stage.',
                icon: IconRocket,
                heroImage: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1920&q=80',
                features: ['Growth Strategy & Planning', 'Funnel Optimization', 'Retention Marketing', 'Viral & Referral Campaigns', 'Product-Led Growth Tactics', 'Data Analytics & Experimentation'],
                benefits: ['Sustainable long-term growth', 'Lower customer acquisition cost', 'Higher customer lifetime value', 'Rapid experimentation cycles'],
            },
            {
                slug: 'google-ads-management',
                name: 'Google Ads Management',
                description: 'Expert Google Ads management that puts your business in front of high-intent customers exactly when they are searching for your products or services.',
                icon: IconBrandGoogle,
                heroImage: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=1920&q=80',
                features: ['Search & Display Campaigns', 'Shopping Ads Management', 'YouTube Video Ads', 'Remarketing & Retargeting', 'Keyword Research & Bidding', 'Quality Score Optimization'],
                benefits: ['Immediate visibility on Google', 'Reach high-intent customers', 'Precise budget control', 'Detailed performance tracking'],
            },
            {
                slug: 'facebook-instagram-ads',
                name: 'Facebook & Instagram Ads',
                description: 'Targeted social advertising on Meta platforms to reach your ideal audience with visually compelling creatives that drive engagement and conversions.',
                icon: IconBrandFacebook,
                heroImage: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=1920&q=80',
                features: ['Audience Targeting & Lookalikes', 'Creative Ad Design', 'Carousel & Video Ads', 'Lead Generation Campaigns', 'Retargeting & Custom Audiences', 'Campaign Optimization & Scaling'],
                benefits: ['Access 3B+ active users', 'Advanced audience targeting', 'Visual-first ad formats', 'Lower cost per lead'],
            },
        ],
    },
    {
        slug: 'website-development',
        name: 'Website Development',
        shortName: 'Web Development',
        description: 'Custom websites and web applications built with modern technologies for performance, scalability, and exceptional user experience.',
        icon: IconCode,
        color: 'emerald',
        heroImage: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=1920&q=80',
        stats: [
            { value: '500+', label: 'Websites Built' },
            { value: '99.9%', label: 'Uptime Rate' },
            { value: '< 2s', label: 'Load Time' },
            { value: '100+', label: 'E-Commerce Stores' },
        ],
        subServices: [
            {
                slug: 'web-design',
                name: 'Web Design Services',
                description: 'Beautiful, conversion-focused website designs that capture your brand essence and turn visitors into customers with intuitive navigation and stunning visuals.',
                icon: IconPalette,
                heroImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1920&q=80',
                features: ['Custom Website Design', 'Responsive & Mobile-First', 'Brand-Aligned Aesthetics', 'Interactive Prototypes', 'Cross-Browser Compatibility', 'Performance Optimization'],
                benefits: ['First impressions that convert', 'Mobile-optimized experiences', 'Consistent brand identity', 'Faster loading websites'],
            },
            {
                slug: 'ui-ux-design',
                name: 'UI/UX Design',
                description: 'User-centered design that combines beautiful interfaces with intuitive experiences, ensuring every interaction delights and converts your visitors.',
                icon: IconLayout,
                heroImage: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=1920&q=80',
                features: ['User Research & Personas', 'Wireframing & Prototyping', 'Visual Interface Design', 'Usability Testing', 'Design Systems', 'Interaction Design'],
                benefits: ['Higher user satisfaction', 'Reduced bounce rates', 'Increased conversions', 'Better user retention'],
            },
            {
                slug: 'wordpress-development',
                name: 'WordPress Development',
                description: 'Custom WordPress websites and themes that give you complete control over your content with powerful functionality and easy management.',
                icon: IconBrandWordpress,
                heroImage: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=1920&q=80',
                features: ['Custom Theme Development', 'Plugin Development', 'WooCommerce Integration', 'Speed Optimization', 'Security Hardening', 'Migration & Support'],
                benefits: ['Easy content management', '60,000+ plugins available', 'SEO-friendly architecture', 'Cost-effective solutions'],
            },
            {
                slug: 'shopify-development',
                name: 'Shopify Development',
                description: 'Professional Shopify store development to launch and scale your e-commerce business with custom themes, apps, and conversion-optimized checkout experiences.',
                icon: IconShoppingBag,
                heroImage: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1920&q=80',
                features: ['Custom Shopify Themes', 'App Integration & Development', 'Payment Gateway Setup', 'Inventory Management', 'Checkout Optimization', 'Shopify Plus Solutions'],
                benefits: ['Quick store launch', 'Secure payment processing', 'Scalable infrastructure', '24/7 Shopify support'],
            },
            {
                slug: 'landing-page-design',
                name: 'Landing Page Design',
                description: 'High-converting landing pages designed to capture leads and drive sales, with A/B tested layouts and persuasive copy that maximizes your ad spend.',
                icon: IconDeviceDesktop,
                heroImage: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=1920&q=80',
                features: ['Conversion-Optimized Design', 'A/B Testing Ready', 'Lead Capture Forms', 'Fast Loading Pages', 'CRM Integration', 'Analytics & Heatmaps'],
                benefits: ['Higher conversion rates', 'Better ad ROI', 'Faster campaign launch', 'Data-backed optimization'],
            },
        ],
    },
    {
        slug: 'search-engine-optimization-seo',
        name: 'SEO Services',
        shortName: 'SEO',
        description: 'Comprehensive search engine optimization strategies to boost your organic rankings, drive qualified traffic, and dominate search results.',
        icon: IconSearch,
        color: 'orange',
        heroImage: 'https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=1920&q=80',
        stats: [
            { value: '10K+', label: 'Keywords Ranked' },
            { value: '200%', label: 'Avg Traffic Growth' },
            { value: '50+', label: 'Industries Served' },
            { value: '#1', label: 'Page Rankings' },
        ],
        subServices: [
            {
                slug: 'local-seo',
                name: 'Local SEO',
                description: 'Dominate local search results and Google Maps to attract nearby customers actively searching for your products and services in your area.',
                icon: IconMapPin,
                heroImage: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1920&q=80',
                features: ['Google Business Profile Optimization', 'Local Citation Building', 'NAP Consistency Management', 'Local Link Building', 'Review Management', 'Local Schema Markup'],
                benefits: ['Rank in Google Maps pack', 'Attract nearby customers', 'Build local authority', 'Increase foot traffic'],
            },
            {
                slug: 'ecommerce-seo',
                name: 'Ecommerce SEO',
                description: 'Specialized SEO strategies for online stores to drive organic traffic to product pages, increase visibility, and boost sales without paid advertising.',
                icon: IconShoppingCart,
                heroImage: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1920&q=80',
                features: ['Product Page Optimization', 'Category Structure & Navigation', 'Schema Markup for Products', 'Site Speed Optimization', 'Content Strategy for E-commerce', 'Competitor Analysis'],
                benefits: ['Higher product visibility', 'Increased organic sales', 'Lower acquisition costs', 'Better user experience'],
            },
            {
                slug: 'technical-seo',
                name: 'Technical SEO',
                description: 'In-depth technical audits and optimizations to ensure search engines can crawl, index, and rank your website efficiently for maximum visibility.',
                icon: IconSettings,
                heroImage: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=1920&q=80',
                features: ['Site Architecture Optimization', 'Core Web Vitals', 'Crawl Budget Management', 'XML Sitemap & Robots.txt', 'Structured Data Implementation', 'Mobile-First Optimization'],
                benefits: ['Faster indexing', 'Improved crawlability', 'Better page speed', 'Higher rankings potential'],
            },
            {
                slug: 'on-page-seo',
                name: 'On Page SEO',
                description: 'Optimize every element of your web pages — from content and keywords to meta tags and internal linking — for maximum search engine visibility.',
                icon: IconFileText,
                heroImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1920&q=80',
                features: ['Keyword Research & Mapping', 'Meta Title & Description Optimization', 'Header Tag Structure', 'Content Optimization', 'Internal Linking Strategy', 'Image SEO & Alt Tags'],
                benefits: ['Higher keyword rankings', 'Better click-through rates', 'Improved content relevance', 'Enhanced user engagement'],
            },
            {
                slug: 'off-page-seo',
                name: 'Off Page SEO',
                description: 'Build your website\'s authority and trustworthiness through strategic link building, brand mentions, and digital PR campaigns.',
                icon: IconLink,
                heroImage: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1920&q=80',
                features: ['High-Quality Link Building', 'Guest Posting & Outreach', 'Digital PR Campaigns', 'Brand Mention Monitoring', 'Competitor Backlink Analysis', 'Social Bookmarking'],
                benefits: ['Higher domain authority', 'Improved search rankings', 'Increased referral traffic', 'Stronger brand presence'],
            },
            {
                slug: 'seo-audit',
                name: 'SEO Audit',
                description: 'Comprehensive SEO audits that uncover issues holding your website back and provide actionable recommendations to improve your search performance.',
                icon: IconReportAnalytics,
                heroImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1920&q=80',
                features: ['Technical SEO Audit', 'Content Quality Analysis', 'Backlink Profile Review', 'Competitor Benchmarking', 'Page Speed Analysis', 'Mobile Usability Audit'],
                benefits: ['Identify SEO issues', 'Prioritized action plan', 'Competitive insights', 'Performance benchmarks'],
            },
            {
                slug: 'ai-seo',
                name: 'AI SEO',
                description: 'Leverage artificial intelligence and machine learning to supercharge your SEO strategy with predictive analytics, automated optimization, and smart content creation.',
                icon: IconRobot,
                heroImage: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1920&q=80',
                features: ['AI Content Optimization', 'Predictive Keyword Analysis', 'Automated Technical Fixes', 'AI-Powered Content Creation', 'Smart Internal Linking', 'Search Intent Analysis'],
                benefits: ['Faster optimization cycles', 'Predictive ranking insights', 'Scalable content creation', 'Competitive advantage'],
            },
        ],
    },
    {
        slug: 'branding',
        name: 'Branding Services',
        shortName: 'Branding',
        description: 'Build a powerful brand identity that resonates with your audience and sets you apart from the competition with memorable design and strategy.',
        icon: IconBrush,
        color: 'violet',
        heroImage: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=1920&q=80',
        stats: [
            { value: '300+', label: 'Brands Created' },
            { value: '50+', label: 'Industries Covered' },
            { value: '98%', label: 'Client Satisfaction' },
            { value: '1000+', label: 'Design Projects' },
        ],
        subServices: [
            {
                slug: 'brand-identity-design',
                name: 'Brand Identity Design',
                description: 'Comprehensive brand identity systems that define your visual language — from strategy and positioning to complete brand guidelines that ensure consistency.',
                icon: IconSparkles,
                heroImage: 'https://images.unsplash.com/photo-1634942537034-2531766767d1?w=1920&q=80',
                features: ['Brand Strategy & Positioning', 'Visual Identity System', 'Brand Guidelines Document', 'Typography & Color Palette', 'Brand Voice & Messaging', 'Brand Collateral Design'],
                benefits: ['Consistent brand experience', 'Professional brand image', 'Stronger market positioning', 'Higher brand recall'],
            },
            {
                slug: 'logo-design',
                name: 'Logo Design',
                description: 'Iconic logo designs that capture the essence of your brand in a single mark — memorable, versatile, and designed to stand the test of time.',
                icon: IconPencilPlus,
                heroImage: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=1920&q=80',
                features: ['Custom Logo Concepts', 'Multiple Design Variations', 'Vector & Scalable Formats', 'Brand Color Exploration', 'Typography Selection', 'Logo Usage Guidelines'],
                benefits: ['Memorable brand mark', 'Professional first impression', 'Versatile across media', 'Unique to your brand'],
            },
            {
                slug: 'graphic-design',
                name: 'Graphic Design',
                description: 'Eye-catching graphic design for all your marketing needs — from social media graphics and brochures to presentations and packaging design.',
                icon: IconPhoto,
                heroImage: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1920&q=80',
                features: ['Social Media Graphics', 'Print Design & Brochures', 'Presentation Design', 'Infographic Creation', 'Packaging Design', 'Marketing Collateral'],
                benefits: ['Professional visual content', 'Consistent brand aesthetics', 'Higher engagement rates', 'Versatile design assets'],
            },
            {
                slug: 'creative-for-ads',
                name: 'Creative for Ads',
                description: 'Scroll-stopping ad creatives designed to capture attention and drive action across Google, Facebook, Instagram, and other advertising platforms.',
                icon: IconAd,
                heroImage: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=1920&q=80',
                features: ['Display Ad Design', 'Social Media Ad Creatives', 'Video Ad Production', 'Carousel Ad Design', 'Story & Reel Creatives', 'Ad Copy & CTA Design'],
                benefits: ['Higher click-through rates', 'Better ad performance', 'Consistent ad branding', 'Platform-optimized designs'],
            },
            {
                slug: 'performance-creatives',
                name: 'Performance Creatives',
                description: 'Data-backed creative design optimized for conversions — combining design best practices with performance data to create ads that actually sell.',
                icon: IconChartBar,
                heroImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1920&q=80',
                features: ['Data-Driven Design', 'A/B Creative Testing', 'Conversion-Optimized Layouts', 'Dynamic Creative Optimization', 'Performance Analytics', 'Iterative Design Process'],
                benefits: ['Higher conversion rates', 'Lower cost per acquisition', 'Data-backed decisions', 'Continuous improvement'],
            },
        ],
    },
    {
        slug: 'social-media-marketing',
        name: 'Social Media Marketing',
        shortName: 'Social Media',
        description: 'Strategic social media management and marketing to build your brand, engage your audience, and drive growth across all major social platforms.',
        icon: IconBrandInstagram,
        color: 'pink',
        heroImage: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=1920&q=80',
        stats: [
            { value: '50M+', label: 'Reach Generated' },
            { value: '200+', label: 'Brands Managed' },
            { value: '10K+', label: 'Posts Created' },
            { value: '500%', label: 'Avg Engagement Growth' },
        ],
        subServices: [
            {
                slug: 'social-media-management',
                name: 'Social Media Management',
                description: 'End-to-end social media management — from content planning and creation to publishing, community management, and performance reporting.',
                icon: IconSpeakerphone,
                heroImage: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=1920&q=80',
                features: ['Content Calendar Planning', 'Post Creation & Scheduling', 'Community Management', 'Engagement Monitoring', 'Monthly Reporting', 'Platform Strategy'],
                benefits: ['Consistent brand presence', 'Time savings for your team', 'Professional content quality', 'Growth-focused strategy'],
            },
            {
                slug: 'instagram-marketing',
                name: 'Instagram Marketing',
                description: 'Grow your Instagram presence with strategic content, Reels, Stories, and targeted ads that build a loyal following and drive real business results.',
                icon: IconBrandInstagram,
                heroImage: 'https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=1920&q=80',
                features: ['Feed & Stories Strategy', 'Reels & Short Video Content', 'Hashtag Optimization', 'Instagram Shopping Setup', 'Influencer Collaborations', 'Instagram Ads Management'],
                benefits: ['Larger engaged following', 'Higher brand visibility', 'Direct sales via Instagram', 'Stronger visual branding'],
            },
            {
                slug: 'facebook-marketing',
                name: 'Facebook Marketing',
                description: 'Leverage Facebook\'s massive user base and advanced targeting to reach your ideal customers with compelling content and high-performing ad campaigns.',
                icon: IconBrandFacebook,
                heroImage: 'https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=1920&q=80',
                features: ['Facebook Page Management', 'Facebook Ads Campaigns', 'Audience Targeting & Segmentation', 'Facebook Groups Strategy', 'Messenger Marketing', 'Lead Generation Ads'],
                benefits: ['Reach 3B+ users', 'Advanced targeting options', 'Cost-effective advertising', 'Strong lead generation'],
            },
            {
                slug: 'linkedin-marketing',
                name: 'LinkedIn Marketing',
                description: 'Professional LinkedIn marketing for B2B businesses — grow your thought leadership, generate quality leads, and build valuable business connections.',
                icon: IconBrandLinkedin,
                heroImage: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1920&q=80',
                features: ['LinkedIn Company Page Optimization', 'Thought Leadership Content', 'LinkedIn Ads Management', 'InMail Campaigns', 'Employee Advocacy Programs', 'Lead Generation'],
                benefits: ['Quality B2B leads', 'Professional brand positioning', 'Decision-maker access', 'Thought leadership'],
            },
            {
                slug: 'youtube-marketing',
                name: 'YouTube Marketing',
                description: 'YouTube channel management and video marketing strategies to grow your subscriber base, increase watch time, and drive traffic and conversions.',
                icon: IconBrandYoutube,
                heroImage: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=1920&q=80',
                features: ['Channel Strategy & Setup', 'Video SEO Optimization', 'Thumbnail & Title Optimization', 'YouTube Ads Management', 'Content Calendar & Production', 'Analytics & Reporting'],
                benefits: ['Massive video audience reach', 'Long-form content authority', 'SEO benefits from YouTube', 'Higher engagement rates'],
            },
            {
                slug: 'influencer-marketing',
                name: 'Influencer Marketing',
                description: 'Connect with the right influencers to amplify your brand message — from micro-influencers to celebrities, we manage end-to-end influencer campaigns.',
                icon: IconUsers,
                heroImage: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=1920&q=80',
                features: ['Influencer Research & Vetting', 'Campaign Strategy & Brief', 'Content Collaboration', 'Contract & Negotiation', 'Performance Tracking', 'ROI Measurement'],
                benefits: ['Authentic brand reach', 'Higher trust with audience', 'Content creation support', 'Measurable campaign results'],
            },
            {
                slug: 'short-video-marketing',
                name: 'Short Video Marketing',
                description: 'Create viral short-form video content for Instagram Reels, YouTube Shorts, and other platforms to capture attention and drive massive organic reach.',
                icon: IconVideo,
                heroImage: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1920&q=80',
                features: ['Reels & Shorts Strategy', 'Script Writing & Storyboarding', 'Video Production & Editing', 'Trend & Audio Research', 'Cross-Platform Distribution', 'Performance Analysis'],
                benefits: ['Massive organic reach', 'Higher engagement rates', 'Trend-driven content', 'Cost-effective marketing'],
            },
        ],
    },
    {
        slug: 'automation',
        name: 'Automation Solutions',
        shortName: 'Automation',
        description: 'Streamline your business operations with intelligent automation solutions that save time, reduce costs, and scale your marketing and sales efforts.',
        icon: IconSettingsAutomation,
        color: 'indigo',
        heroImage: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1920&q=80',
        stats: [
            { value: '70%', label: 'Time Saved' },
            { value: '200+', label: 'Automations Built' },
            { value: '5X', label: 'Productivity Increase' },
            { value: '40%', label: 'Cost Reduction' },
        ],
        subServices: [
            {
                slug: 'marketing-automation',
                name: 'Marketing Automation',
                description: 'Automate your marketing workflows — from lead nurturing and email sequences to campaign triggers and personalized customer journeys at scale.',
                icon: IconSettingsAutomation,
                heroImage: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=1920&q=80',
                features: ['Workflow Automation Design', 'Drip Campaign Setup', 'Lead Scoring & Routing', 'Trigger-Based Campaigns', 'Multi-Channel Automation', 'Performance Analytics'],
                benefits: ['Save hours weekly', 'Consistent lead nurturing', 'Higher conversion rates', 'Scalable operations'],
            },
            {
                slug: 'crm-automation',
                name: 'CRM Automation',
                description: 'Automate your CRM processes to manage leads, track interactions, and nurture relationships efficiently — so your sales team can focus on closing deals.',
                icon: IconDatabase,
                heroImage: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1920&q=80',
                features: ['CRM Setup & Configuration', 'Contact & Deal Automation', 'Pipeline Management', 'Task & Follow-up Reminders', 'Reporting Dashboards', 'Integration with Marketing Tools'],
                benefits: ['Streamlined sales process', 'No leads fall through cracks', 'Better customer insights', 'Faster deal closure'],
            },
            {
                slug: 'lead-automation',
                name: 'Lead Automation',
                description: 'Automate your entire lead management process — from capture and qualification to routing and follow-up — ensuring no opportunity is ever missed.',
                icon: IconFilter,
                heroImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1920&q=80',
                features: ['Lead Capture Automation', 'Lead Scoring Models', 'Auto-Assignment Rules', 'Follow-up Sequences', 'Lead Quality Tracking', 'Multi-Source Integration'],
                benefits: ['Faster lead response', 'Higher lead quality', 'Automated follow-ups', 'Zero lead leakage'],
            },
            {
                slug: 'email-automation',
                name: 'Email Automation',
                description: 'Set up intelligent email automation workflows that deliver the right message to the right person at the right time — onboarding, nurturing, and re-engagement.',
                icon: IconMail,
                heroImage: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=1920&q=80',
                features: ['Welcome & Onboarding Series', 'Drip Email Campaigns', 'Behavioral Trigger Emails', 'Cart Abandonment Recovery', 'Re-engagement Campaigns', 'A/B Testing & Optimization'],
                benefits: ['Higher open rates', 'Personalized communication', 'Revenue on autopilot', 'Better customer retention'],
            },
            {
                slug: 'sales-funnel-automation',
                name: 'Sales Funnel Automation',
                description: 'Build and automate your complete sales funnel — from awareness to conversion — with landing pages, email sequences, and conversion tracking.',
                icon: IconTrendingUp,
                heroImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1920&q=80',
                features: ['Funnel Strategy & Design', 'Landing Page Creation', 'Email Sequence Building', 'Upsell & Cross-sell Flows', 'Conversion Tracking', 'Funnel Analytics & Optimization'],
                benefits: ['Automated revenue generation', 'Higher conversion rates', 'Predictable sales pipeline', 'Scalable sales process'],
            },
            {
                slug: 'ai-marketing-automation',
                name: 'AI Marketing Automation',
                description: 'Next-generation marketing automation powered by artificial intelligence — predictive analytics, smart segmentation, and self-optimizing campaigns.',
                icon: IconRobot,
                heroImage: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1920&q=80',
                features: ['AI-Powered Segmentation', 'Predictive Lead Scoring', 'Smart Content Personalization', 'Automated A/B Testing', 'Chatbot Integration', 'Predictive Analytics'],
                benefits: ['Smarter automation', 'Higher personalization', 'Better predictions', 'Self-improving campaigns'],
            },
        ],
    },
    {
        slug: 'managed-services',
        name: 'Managed Services',
        shortName: 'Managed Services',
        description: 'End-to-end managed marketing services — let our expert team handle your entire digital marketing while you focus on running your business.',
        icon: IconBriefcase,
        color: 'teal',
        heroImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1920&q=80',
        stats: [
            { value: '100+', label: 'Managed Clients' },
            { value: '24/7', label: 'Dedicated Support' },
            { value: '95%', label: 'Retention Rate' },
            { value: '3X', label: 'Avg Growth Rate' },
        ],
        subServices: [
            {
                slug: 'digital-marketing-managed',
                name: 'Digital Marketing Managed',
                description: 'Complete digital marketing management — strategy, execution, optimization, and reporting — all handled by a dedicated team of marketing experts.',
                icon: IconTargetArrow,
                heroImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1920&q=80',
                features: ['Dedicated Marketing Team', 'Multi-Channel Strategy', 'Campaign Management', 'Monthly Performance Reports', 'Regular Strategy Calls', 'Continuous Optimization'],
                benefits: ['Expert team at lower cost', 'Consistent marketing execution', 'Full transparency', 'Faster results'],
            },
            {
                slug: 'seo-managed',
                name: 'SEO Managed Services',
                description: 'Fully managed SEO services where our expert team handles your entire SEO strategy — from technical fixes and content creation to link building and reporting.',
                icon: IconSearch,
                heroImage: 'https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=1920&q=80',
                features: ['Dedicated SEO Team', 'Technical SEO Management', 'Content Creation & Optimization', 'Link Building Campaigns', 'Monthly SEO Reports', 'Competitor Monitoring'],
                benefits: ['Hands-off SEO growth', 'Expert-driven strategy', 'Consistent content creation', 'Long-term organic growth'],
            },
            {
                slug: 'ppc-managed',
                name: 'PPC Managed Services',
                description: 'Expert PPC management across Google, Facebook, and other platforms — our team handles campaign setup, optimization, and reporting to maximize your ad ROI.',
                icon: IconBrandGoogle,
                heroImage: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=1920&q=80',
                features: ['Multi-Platform PPC Management', 'Campaign Setup & Optimization', 'Bid Strategy & Budget Management', 'Ad Creative Production', 'Conversion Tracking', 'Weekly Performance Reports'],
                benefits: ['Higher ROAS', 'Expert bid management', 'Multi-platform expertise', 'Transparent reporting'],
            },
            {
                slug: 'social-media-managed',
                name: 'Social Media Managed',
                description: 'Full-service social media management — content creation, community management, paid ads, and reporting — all managed by our dedicated social team.',
                icon: IconBrandInstagram,
                heroImage: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=1920&q=80',
                features: ['Content Creation & Design', 'Multi-Platform Management', 'Community Engagement', 'Paid Social Campaigns', 'Monthly Reporting', 'Strategy Reviews'],
                benefits: ['Professional content quality', 'Consistent posting', 'Active community', 'Growth-focused approach'],
            },
            {
                slug: 'startup-marketing',
                name: 'Startup Marketing',
                description: 'Go-to-market strategies and growth marketing for startups — from brand building and customer acquisition to fundraising support and rapid scaling.',
                icon: IconRocket,
                heroImage: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=1920&q=80',
                features: ['Go-to-Market Strategy', 'Brand Building & Positioning', 'Growth Hacking', 'Investor-Ready Marketing', 'Product-Market Fit Validation', 'Rapid Scaling Strategies'],
                benefits: ['Faster market entry', 'Cost-effective growth', 'Investor-ready metrics', 'Scalable foundations'],
            },
            {
                slug: 'saas-marketing',
                name: 'SaaS Marketing',
                description: 'Specialized marketing for SaaS companies — from trial conversions and user onboarding to retention marketing and reducing churn at every stage.',
                icon: IconWorldWww,
                heroImage: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=1920&q=80',
                features: ['SaaS Growth Strategy', 'Trial-to-Paid Conversion', 'Product-Led Growth', 'Content & SEO Marketing', 'Email Onboarding Flows', 'Churn Reduction Strategies'],
                benefits: ['Higher MRR growth', 'Better trial conversion', 'Lower churn rate', 'Scalable acquisition'],
            },
            {
                slug: 'ecommerce-marketing',
                name: 'Ecommerce Marketing',
                description: 'Complete marketing management for e-commerce businesses — from product feed optimization and shopping ads to email flows and conversion rate optimization.',
                icon: IconBuildingStore,
                heroImage: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1920&q=80',
                features: ['Product Feed Optimization', 'Shopping Ads Management', 'Email & SMS Marketing', 'Conversion Rate Optimization', 'Retargeting Campaigns', 'Marketplace Management'],
                benefits: ['Higher sales volume', 'Better product visibility', 'Repeat customer revenue', 'Multi-channel presence'],
            },
            {
                slug: 'b2b-marketing',
                name: 'B2B Marketing',
                description: 'Strategic B2B marketing that generates high-quality leads and builds lasting business relationships through account-based marketing and thought leadership.',
                icon: IconBulb,
                heroImage: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=1920&q=80',
                features: ['Account-Based Marketing', 'LinkedIn & Email Outreach', 'Content Marketing & Whitepapers', 'Webinar & Event Marketing', 'Lead Nurturing Campaigns', 'Sales Enablement'],
                benefits: ['Quality B2B leads', 'Shorter sales cycles', 'Stronger partnerships', 'Higher deal values'],
            },
        ],
    },
];

export default serviceCategories;
